source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
inhibit_all_warnings!

target 'bridge_iOS' do
    pod 'AFNetworking', '~> 3.0.1'
    pod 'MJExtension', '~> 2.5.14'
    pod 'FMDB', '~> 2.6.2'
    pod 'SDAutoLayout', '~> 2.1.8'
    pod 'ReactiveCocoa', :git => 'https://github.com/zhao0/ReactiveCocoa.git', :tag => '2.5.2'
    pod 'UMengAnalytics', '~> 4.1.8'
    pod 'RDVTabBarController', '~> 1.1.9'
    pod 'SVProgressHUD', '~> 2.1.2'
    pod 'WebViewJavascriptBridge', '~> 6.0.2'
end

